"""netie_init - stamp the Netie operating system into a repo. Idempotent.

Creates the five governed files if missing and maintains a marker-delimited block in
CLAUDE.md / AGENTS.md that tells a cold session where the state lives.

Re-running is safe: the block between the markers is replaced, never appended, so this
can run on every repo every time without accumulating.

    python D:\\Netie\\scripts\\netie_init.py D:\\DMS
    python D:\\Netie\\scripts\\netie_init.py --all
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

NETIE = Path(__file__).resolve().parents[1]

BEGIN = "<!-- NETIE:BEGIN - generated by netie_init.py, do not hand-edit -->"
END = "<!-- NETIE:END -->"

#: Repos the estate governs. Product name -> path.
REPOS: dict[str, Path] = {
    "Cortex": Path("D:/Cortex"),
    "DMS": Path("D:/DMS"),
    "OpenVault": Path("D:/OpenVault"),
    "AirGPT": Path("D:/AirGPT"),
    "Space": Path("D:/Space"),
    "Pointer": Path("D:/Pointer"),
    "Constructor": Path("D:/constructor"),
    # Fold into Crew when Crew exists. Not Guacamole.
    "Control": Path("D:/netie-control"),
    "KB": Path("D:/Netie-KB"),
    # Planned: stamp when the repo exists. Not a second Cortex.
    "Crew": Path("D:/Cortex-Crew"),
}

# What each product repo imports after `uv add` Netie.
# Cortex cannot uv-add Netie.git: it already owns the package name `netie`.
CALLERS: dict[str, str] = {
    "Cortex": "from CortexOS.constitution.cortex_path import run_question, WRITE_ACTIONS",
    "DMS": "from netie.dms import answer_or_abstain, browse_or_abstain, mint_object",
    "OpenVault": "from netie.route import host_switchyard, report_deploy, assist_free_pool; from netie.crew import refuse_crew_gate",
    "AirGPT": "from netie.airgpt import retrieve_space, chunk_table",
    "Space": "from netie.space import chat_preview, leave",
    "Pointer": "from netie.pointer import bind_computer, bind_pointer_skill, invoke_hand, guard_observe",
    "Constructor": "from netie.route import compile_graph, compile_ir",
    "Control": "from netie.control import project_board, project_session, MAX_BOARD_CHARS, board_index",
    "KB": "from netie.kb import show_brief, lookup, list_briefs",
    "Crew": "from netie.crew import bind_deep_agent, crew_harness_profile, TokenBudget, dispatch_seat, persist, resume, register_skill, register_from_kb, register_index, mint_issue, board_from_runs",
}


def _caller(product: str) -> str:
    return CALLERS.get(product, "from netie.crew import bind_deep_agent")


def _install_line(product: str) -> str:
    if product == "Cortex":
        return (
            "Do not `uv add` Netie.git here: Cortex already owns the Python "
            "package name `netie` (CortexOS alias). Apply "
            "`docs/patches/cortex-netie-path.patch` from Netie-AI/Netie."
        )
    return "`uv add git+https://github.com/Netie-AI/Netie.git`"


def _block(product: str) -> str:
    """The generated block. Same in every repo except the PRD pointer."""
    caller = _caller(product)
    install = _install_line(product)
    return f"""{BEGIN}

## Netie operating system

Cold start, in order: this file, then `D:\\Netie\\Software Blueprint\\{product}\\` (PRD + feedback
ledger), `gh issue list` (live tickets, never a markdown backlog), `STATUS.md` (max 60 lines).
`D:\\Netie` is `Netie-AI/Netie`; clone it if missing.

**Route first.** A feature request or defect goes to `prd-agent` before anyone builds it. It
decides: open epic, reopen a closed one, or PRD amendment for the founder.

**Agents.** `prd-agent` -> `epic-agent` -> `ticket-runner`, on the model you selected.
Fan-out subagents only: Sonnet in Claude Code, Grok 4.5 high or Composer 2.5 in Cursor.

**Five files, no sixth.** `CLAUDE.md` law, `docs/ACTIVE.md` map, `STATUS.md` state,
`CHANGELOG.md` history, `PARKING_LOT.md` deferred (each entry has an unlock condition).
Decisions: `docs/decisions/DR-NNNN-*.md`. Full law: `D:\\Netie\\Internal\\Rules\\DOCUMENT_SYSTEM.md`.

**Product caller.** {install} Then `{caller}`. The wheel ships contracts as `netie._contracts`.
Do not clone Grok Bot reconstructed. Do not vendor OpenWork `ee/`. Cortex is not Claude Code.

**Upstream code.** Fork and rebrand only what `D:\\Netie\\ecosystem\\ECOSYSTEM.md` marks
fork-rebrand or fork-strip (DR-0002). Never edit a LICENSE or NOTICE. Host or block the rest.

{END}"""


def _readme_block(product: str) -> str:
    """Human-facing. Shorter than the agent block - a person reads this once."""
    return f"""{BEGIN}

## How work happens here

You write the PRD. `prd-agent` slices it into epics, `epic-agent` turns one epic into tickets,
`ticket-runner` executes them, and `epic-agent` re-checks that the epic is really done.

Just say what you want in a new session: the agent reads `CLAUDE.md` and knows where things
live. Report a bug or ask for a feature anywhere; it is routed to the PRD Agent and recorded
in the feedback ledger, so it still lands in the right epic weeks later.

| You want | Look at |
|---|---|
| what we build and why | `D:\\Netie\\Software Blueprint\\{product}\\` |
| the live task list | GitHub Issues on this repo |
| what is true right now | `STATUS.md` |
| why the code is shaped this way | `docs/decisions/` |
| the rules every repo follows | `D:\\Netie\\NETIE.md` |

Search lessons before non-trivial work: `python D:\\Netie-KB\\scripts\\kb.py search "<keywords>"`.
Set up another repo: `python D:\\Netie\\scripts\\netie_init.py <path>`

{END}"""


SEEDS: dict[str, str] = {
    "STATUS.md": """# STATUS

**Hard cap: 60 lines.** Older narrative moves to CHANGELOG.md; it does not accumulate here.

## Now

_Max 3. Problems, not features. Anything here longer than two appetites is killed or
moved to Later - no meeting required._

## Next

## Later
""",
    "PARKING_LOT.md": """# PARKING_LOT

Deferred work. **Every entry carries an unlock condition.** An entry with no condition is
not parked, it is abandoned - delete it.

| ID | Item | Unlock condition |
|----|------|------------------|
""",
    "CHANGELOG.md": """# CHANGELOG

Append-only. Never edited, only added to. Newest first.
""",
    "docs/ACTIVE.md": """# Active map

What exists in this repo and where. Update when structure changes, not when state changes
- state lives in STATUS.md.
""",
}

DR0001 = """---
status: accepted
date: {date}
decision-makers: founder
---

# DR-0001 - Record decisions in this repo

## Context and Problem Statement

Decisions were being re-litigated every session because the reasoning behind them lived
in chat logs rather than in the repo.

## Considered Options

- Keep decisions in chat and hope they are remembered
- A wiki alongside the repo
- Decision records in the repo, changed by pull request

## Decision Outcome

Decision records in the repo, at `docs/decisions/DR-NNNN-kebab-title.md`.

Opened with `status: proposed` **as a pull request** - the PR is the RFC and the thread
is the review. On merge, status flips to `accepted`. Superseded records are kept and
marked, never deleted or edited.

## Consequences

Positive: the argument lives in the same history as the code, and an agent can read why
before proposing the same thing again.

Negative: one more file per decision, and a threshold judgement about what deserves one.
Write a DR only when it crosses a repo boundary, touches the contract / ledger / manifest
enforcer / a protected path, is expensive to reverse, or an agent would otherwise
re-litigate it. Everything else is a commit message.

## Confirmation

This file existing is the confirmation for DR-0001. Every later DR must name a test file
that exists - a decision naming a non-existent enforcer is a wish, not a control.
"""


#: Existing files that already serve a governed role under a different name. Seeding the
#: canonical name on top of these would create a second backlog, which is the exact
#: failure this system exists to prevent. Rename by hand if you want the canonical name.
ALIASES: dict[str, tuple[str, ...]] = {
    "PARKING_LOT.md": ("PARKINGLOT.md", "parkinglot.markdown", "parking_lot.md"),
    "STATUS.md": ("status.md",),
    "CHANGELOG.md": ("CHANGELOG_DMS.md", "changelog.md"),
    "docs/ACTIVE.md": ("docs/active.md",),
}


def _already_served(repo: Path, canonical: str) -> str | None:
    """Return an existing alias filling this role, if any."""
    for alt in ALIASES.get(canonical, ()):
        if (repo / alt).exists():
            return alt
    return None


NEW_CLAUDE_MD = """# CLAUDE.md - {product} agent contract

Read this before any edit.

## Hard rules

_None recorded yet. Add the invariants that must never break in this repo - the ones
where a violation is silent and expensive. If CI enforces one, name the job._

"""


def stamp(repo: Path, product: str, *, dry: bool = False) -> list[str]:
    """Apply the Netie block and seed missing governed files. Returns actions taken."""
    if not repo.is_dir():
        return [f"SKIP {repo} - not a directory"]

    actions: list[str] = []
    block = _block(product)

    # A repo with no CLAUDE.md has no agent contract at all - create a minimal one so the
    # block has a home, rather than silently skipping the repo that needs it most.
    claude = repo / "CLAUDE.md"
    if not claude.is_file():
        if not dry:
            claude.write_text(
                NEW_CLAUDE_MD.format(product=product), encoding="utf-8", newline="\n"
            )
        actions.append("created CLAUDE.md (no agent contract existed)")

    for name in ("CLAUDE.md", "AGENTS.md", "README.md"):
        path = repo / name
        if not path.is_file():
            if dry and name == "CLAUDE.md":
                actions.append("inserted block in CLAUDE.md")
            continue
        block = _readme_block(product) if name == "README.md" else _block(product)
        text = path.read_text(encoding="utf-8")
        if BEGIN in text and END in text:
            head, _, rest = text.partition(BEGIN)
            _, _, tail = rest.partition(END)
            new = f"{head}{block}{tail}"
            verb = "refreshed"
        else:
            # Insert after the first heading so the block is near the top but does not
            # displace the title a human reads first.
            lines = text.splitlines(keepends=True)
            idx = next((i for i, ln in enumerate(lines) if ln.startswith("# ")), -1)
            at = idx + 1 if idx >= 0 else 0
            new = "".join(lines[:at]) + f"\n{block}\n" + "".join(lines[at:])
            verb = "inserted"
        if new != text:
            if not dry:
                path.write_text(new, encoding="utf-8", newline="\n")
            actions.append(f"{verb} block in {name}")

    for rel, body in SEEDS.items():
        path = repo / rel
        if path.exists():
            continue
        alias = _already_served(repo, rel)
        if alias:
            actions.append(f"skipped {rel} - already served by {alias}")
            continue
        if not dry:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body, encoding="utf-8", newline="\n")
        actions.append(f"created {rel}")

    dr = repo / "docs" / "decisions" / "0001-record-decisions-in-this-repo.md"
    if not dr.exists():
        if not dry:
            dr.parent.mkdir(parents=True, exist_ok=True)
            dr.write_text(DR0001.format(date="2026-08-02"), encoding="utf-8", newline="\n")
        actions.append("created docs/decisions/0001-record-decisions-in-this-repo.md")

    return actions or ["already current"]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("repo", nargs="?", help="path to a repo, or omit with --all")
    ap.add_argument("--all", action="store_true", help="every repo in REPOS")
    ap.add_argument("--product", help="product name for the PRD pointer (default: dir name)")
    ap.add_argument("--dry-run", action="store_true", help="report without writing")
    args = ap.parse_args()

    if args.all:
        targets = list(REPOS.items())
    elif args.repo:
        p = Path(args.repo).resolve()
        targets = [(args.product or p.name, p)]
    else:
        ap.error("give a repo path or --all")
        return 2

    for product, path in targets:
        print(f"\n{product}  ({path})")
        for line in stamp(path, product, dry=args.dry_run):
            print(f"  {line}")
    if args.dry_run:
        print("\n(dry run - nothing written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
